export const VIDEO = {
	FETCHING_VIDEOS: 'FETCHING_VIDEOS',
	FETCH_VIDEOS_SUCCESS: 'FETCH_VIDEOS_SUCCESS',
	FETCH_VIDEOS_FAIL: 'FETCH_VIDEOS_FAIL',
}

export const PLAYLISTS = {
	FETCHING_PLAYLISTS: 'FETCHING_PLAYLISTS',
	FETCHING_PLAYLISTS_SUCCESS: 'FETCHING_PLAYLISTS_SUCCESS',
	FETCHING_PLAYLISTS_FAIL: 'FETCHING_PLAYLISTS_FAIL',
	REMOVE_PLAYLIST: 'REMOVE_PLAYLIST',
}

export const PLAYLIST = {
	FETCHING_PLAYLIST: 'FETCHING_PLAYLIST',
	FETCHING_PLAYLIST_SUCCESS: 'FETCHING_PLAYLIST_SUCCESS',
	FETCHING_PLAYLIST_FAIL: 'FETCHING_PLAYLIST_FAIL',
}
